[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
stablecoin_factory = "BNTeFeKEfzeQjWqUY12ohgBr1XA4WbKFBefrHi6DHKMY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/geofrey/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
